theme = "m10c"
baseURL = 'https://blog.iotku.pw/'
languageCode = 'en-us'
title = "iotku's blog"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/iotku"

